import { defaultMapStyleUrl, EVENT_SLUG } from "@/lib/runtime-config";
import type { PortalData } from "@/lib/portal-types";

const heroImage =
  "https://images.unsplash.com/photo-1631995037903-c4f8064c48ae?auto=format&fit=crop&w=2200&q=82";

export const defaultPortalData: PortalData = {
  event: {
    slug: EVENT_SLUG,
    name: "Campeonato de Portugal ORC 2026",
    organizer: "AVELAS",
    level: "Campeonato de Portugal",
    startDate: "2026-07-11",
    endDate: "2026-07-14",
    venueName: "Marina da Figueira da Foz",
    venueCity: "Figueira da Foz",
    courseArea: "Campo 1",
    committee: [
      { name: "Comissão de Regatas", role: "Gestão de prova" },
      { name: "Comité Técnico", role: "Medições e certificados ORC" },
      { name: "Júri", role: "Protestos e decisões" },
    ],
  },
  settings: {
    heroTitle: "Campeonato de Portugal ORC 2026",
    heroSubtitle:
      "Quatro dias de competição costeira, ranking ORC A/B e quadro oficial em tempo real na Figueira da Foz.",
    heroImageUrl: heroImage,
    heroCredit:
      "Imagem demonstrativa: John Bell / Unsplash. Substituir por foto aprovada do Facebook.",
    registrationUrl: "mailto:secretaria@avelas.pt?subject=Inscricao ORC 2026",
    facebookPageUrl:
      "https://www.facebook.com/p/Campeonato-de-Portugal-ORC-100063607089210",
    mapStyleUrl: defaultMapStyleUrl,
    urgentEnabled: true,
    urgentMessage:
      "Portal em modo de lançamento: confirme sempre decisões oficiais no Quadro Oficial de Avisos.",
    urgentHref: "/quadro-oficial",
    partners: [
      { name: "AVELAS" },
      { name: "Marina da Figueira da Foz" },
      { name: "ORC Portugal" },
    ],
  },
  classLabels: {
    ORC_A: "ORC A",
    ORC_B: "ORC B",
  },
  schedule: [
    {
      id: "schedule-1",
      date: "2026-07-11",
      time: "09:00",
      title: "Abertura do secretariado",
      type: "comite",
      location: "Marina da Figueira da Foz",
      description: "Confirmação de presença, documentação e acreditações.",
      highlight: true,
    },
    {
      id: "schedule-2",
      date: "2026-07-11",
      time: "14:00",
      title: "Regata 1 prevista",
      type: "regata",
      location: "Campo 1",
      description: "Primeira largada sujeita a aviso do comité.",
      highlight: true,
    },
    {
      id: "schedule-3",
      date: "2026-07-12",
      time: "12:00",
      title: "Regatas barlavento/sotavento",
      type: "regata",
      location: "Campo 1",
      description: "Programa desportivo publicado pelo comité de regatas.",
    },
    {
      id: "schedule-4",
      date: "2026-07-13",
      time: "12:00",
      title: "Regatas costeiras ORC",
      type: "regata",
      location: "Campo 1",
      description: "Percurso definido nas instruções e avisos do dia.",
    },
    {
      id: "schedule-5",
      date: "2026-07-14",
      time: "17:30",
      title: "Cerimónia de entrega de prémios",
      type: "cerimonia",
      location: "AVELAS",
      description: "Entrega de prémios após publicação de resultados finais.",
      highlight: true,
    },
  ],
  notices: [
    {
      id: "notice-1",
      title: "Quadro Oficial de Avisos aberto",
      body: "Os avisos, alterações, protestos, decisões e resultados oficiais serão publicados nesta área.",
      category: "aviso",
      priority: "importante",
      publishedAt: "2026-07-08T17:00:00.000Z",
    },
    {
      id: "notice-2",
      title: "Documentação base em preparação",
      body: "Anúncio de regata e instruções de regata serão adicionados em PDF pelo comité.",
      category: "anuncio",
      priority: "normal",
      publishedAt: "2026-07-08T17:30:00.000Z",
    },
  ],
  entries: [
    {
      id: "entry-a-1",
      boatName: "Atlântico",
      classCode: "ORC_A",
      className: "ORC A",
      sailNumber: "POR 101",
      skipper: "Skipper A",
      clubName: "AVELAS",
      crew: ["Tripulação A", "Tripulação B"],
      certificateRef: "ORC-DEMO-A",
    },
    {
      id: "entry-a-2",
      boatName: "Foz Racing",
      classCode: "ORC_A",
      className: "ORC A",
      sailNumber: "POR 177",
      skipper: "Skipper B",
      clubName: "Clube visitante",
      certificateRef: "ORC-DEMO-B",
    },
    {
      id: "entry-b-1",
      boatName: "Mondego",
      classCode: "ORC_B",
      className: "ORC B",
      sailNumber: "POR 224",
      skipper: "Skipper C",
      clubName: "AVELAS",
      certificateRef: "ORC-DEMO-C",
    },
  ],
  results: [
    {
      id: "result-general-a",
      title: "Classificação geral provisória",
      classCode: "ORC_A",
      className: "ORC A",
      scope: "geral",
      publishedAt: "2026-07-11T19:00:00.000Z",
      rows: [
        {
          rank: 1,
          boatName: "Atlântico",
          sailNumber: "POR 101",
          skipper: "Skipper A",
          clubName: "AVELAS",
          points: 2,
          raceScores: ["1", "1"],
        },
        {
          rank: 2,
          boatName: "Foz Racing",
          sailNumber: "POR 177",
          skipper: "Skipper B",
          clubName: "Clube visitante",
          points: 5,
          raceScores: ["2", "3"],
        },
      ],
    },
    {
      id: "result-general-b",
      title: "Classificação geral provisória",
      classCode: "ORC_B",
      className: "ORC B",
      scope: "geral",
      publishedAt: "2026-07-11T19:00:00.000Z",
      rows: [
        {
          rank: 1,
          boatName: "Mondego",
          sailNumber: "POR 224",
          skipper: "Skipper C",
          clubName: "AVELAS",
          points: 3,
          raceScores: ["1", "2"],
        },
      ],
    },
  ],
  news: [
    {
      id: "news-1",
      slug: "portal-lancamento",
      title: "Figueira da Foz recebe a frota ORC nacional",
      excerpt:
        "O campeonato reúne a frota ORC A/B numa semana decisiva para o ranking nacional.",
      body: "A AVELAS prepara quatro dias de competição no Campo 1, com quadro oficial digital e acompanhamento visual da prova.",
      imageUrl: heroImage,
      imageCredit: "John Bell / Unsplash",
      publishedAt: "2026-07-08T18:00:00.000Z",
      featured: true,
    },
  ],
  media: [
    {
      id: "media-1",
      title: "Galeria oficial Facebook",
      imageUrl: heroImage,
      sourceUrl:
        "https://www.facebook.com/p/Campeonato-de-Portugal-ORC-100063607089210",
      credit: "Facebook Campeonato de Portugal ORC",
      featured: true,
    },
  ],
  trackingDemo: {
    id: "tracking-demo-1",
    title: "Replay visual Campo 1",
    updatedAt: Date.UTC(2026, 6, 8, 18, 0, 0),
    frames: [
      {
        second: 0,
        positions: [
          {
            entryId: "entry-a-1",
            label: "Atlântico",
            classCode: "ORC_A",
            sailNumber: "POR 101",
            lng: -8.912,
            lat: 40.145,
            sog: 6.4,
            heading: 240,
          },
          {
            entryId: "entry-a-2",
            label: "Foz Racing",
            classCode: "ORC_A",
            sailNumber: "POR 177",
            lng: -8.905,
            lat: 40.151,
            sog: 6.1,
            heading: 238,
          },
          {
            entryId: "entry-b-1",
            label: "Mondego",
            classCode: "ORC_B",
            sailNumber: "POR 224",
            lng: -8.901,
            lat: 40.139,
            sog: 5.7,
            heading: 235,
          },
        ],
      },
      {
        second: 45,
        positions: [
          {
            entryId: "entry-a-1",
            label: "Atlântico",
            classCode: "ORC_A",
            sailNumber: "POR 101",
            lng: -8.925,
            lat: 40.138,
            sog: 7,
            heading: 255,
          },
          {
            entryId: "entry-a-2",
            label: "Foz Racing",
            classCode: "ORC_A",
            sailNumber: "POR 177",
            lng: -8.918,
            lat: 40.145,
            sog: 6.6,
            heading: 252,
          },
          {
            entryId: "entry-b-1",
            label: "Mondego",
            classCode: "ORC_B",
            sailNumber: "POR 224",
            lng: -8.911,
            lat: 40.133,
            sog: 6,
            heading: 248,
          },
        ],
      },
      {
        second: 90,
        positions: [
          {
            entryId: "entry-a-1",
            label: "Atlântico",
            classCode: "ORC_A",
            sailNumber: "POR 101",
            lng: -8.934,
            lat: 40.151,
            sog: 6.8,
            heading: 20,
          },
          {
            entryId: "entry-a-2",
            label: "Foz Racing",
            classCode: "ORC_A",
            sailNumber: "POR 177",
            lng: -8.928,
            lat: 40.156,
            sog: 6.3,
            heading: 24,
          },
          {
            entryId: "entry-b-1",
            label: "Mondego",
            classCode: "ORC_B",
            sailNumber: "POR 224",
            lng: -8.922,
            lat: 40.146,
            sog: 5.9,
            heading: 16,
          },
        ],
      },
    ],
  },
};
